name: Instalar dependencias, ejecutar tests
on:
  push:
    branches:
      - '*'
jobs:
  setup-tests:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest coverage
          echo "Dependencias instaladas correctamente"

      - name: Ejecutar tests
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest coverage
          pytest
